#!/usr/bin/env bash
#Install nginx on your web-01 server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Ngnix HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo ngnix -t
sudo service nginx reload
