#!/usr/bin/env bash
#Install nginx on your web-01 server

apt-get update
apt-get install -y nginx
echo "<html> <body>Hello World!</body> </html>" > /var/www/html/index.nginx-debian.html
service nginx restart
