#!/usr/bin/env bash
# Enable nginx in port 80 and make nginx is not running.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx retart
kill "$(pgrep 'nginx' | head -1)"
