#!/usr/bin/env bash
# This script is displaying 'To infinity and beyond' indefinitely.
#   Displays "I am invincible!!!" in between each iteration.
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
