#!/usr/bin/env bash
# This script prints "Best school" 8 times and "bad luck", "good luck" once time for both
for n in {1..100}
do
	if [ $((n % 3)) -eq 0 ] && [ $((n % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((n % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((n % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$n"
	fi
	n=$(( n + 1 ))
done
