#!/usr/bin/env bash
# Configure a utw firewall to bloc all traffic except
# TCP ports 22(ssh), 443(https), 80(http).

apt-get install ufw
ufw enable
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
